[supervisord]
nodaemon=true

[program:flask]
command=gunicorn --bind 0.0.0.0:5000 app:app
autostart=true
autorestart=true
stderr_logfile=/var/log/gunicorn.err.log
stdout_logfile=/var/log/gunicorn.out.log
